/**
 * Bakes a game's resources into the SDK's generated asset module
 * (the build-time replacement for sdk/assets.ts).
 *
 * Image banks and tilemaps become binary files embedded as cartridge data,
 * sounds and musics become flat integer tables. PNG images listed in the
 * manifest are quantized to the palette and drawn into their banks, as
 * pyxel.images[n].load() would at run time.
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import type { Manifest } from "./manifest.ts";
import { decodePng } from "./png.ts";
import { emptyResource, IMAGE_SIZE, readPalette, readResource, type Resource } from "./pyxres.ts";

export const DEFAULT_COLORS = [
  0x000000, 0x2b335f, 0x7e2072, 0x19959c, 0x8b4852, 0x395c98, 0xa9c1ff, 0xeeeeee, 0xd4186c, 0xd38441, 0xe9c35b,
  0x70c6a9, 0x7696de, 0xa3a3a3, 0xff9798, 0xedc7b0,
];

/** Loads the manifest's resources, palette and images into one resource. */
export function loadGameResource(manifest: Manifest, gameDirectory: string): Resource {
  const resource = manifest.resources ? readResource(resolve(gameDirectory, manifest.resources)) : emptyResource();
  if (manifest.palette) resource.colors = readPalette(resolve(gameDirectory, manifest.palette));
  const colors = resource.colors ?? DEFAULT_COLORS;
  for (const image of manifest.images ?? []) {
    const png = decodePng(readFileSync(resolve(gameDirectory, image.file)));
    const bank = resource.images[image.bank]!;
    for (let y = 0; y < png.height; y++)
      for (let x = 0; x < png.width; x++) {
        const bx = image.x + x,
          by = image.y + y;
        if (bx < 0 || by < 0 || bx >= IMAGE_SIZE || by >= IMAGE_SIZE) continue;
        const at = (y * png.width + x) * 4;
        bank[by * IMAGE_SIZE + bx] = nearestColor(colors, png.rgba[at]!, png.rgba[at + 1]!, png.rgba[at + 2]!);
      }
  }
  return resource;
}

function nearestColor(colors: number[], r: number, g: number, b: number): number {
  let best = 0,
    distance = Infinity;
  colors.forEach((rgb, index) => {
    const d = (((rgb >> 16) & 255) - r) ** 2 + (((rgb >> 8) & 255) - g) ** 2 + ((rgb & 255) - b) ** 2;
    if (d < distance) {
      best = index;
      distance = d;
    }
  });
  return best;
}

const lastUsed = (banks: Uint8Array[]) => banks.findLastIndex((bank) => bank.some((value) => value !== 0)) + 1;
const list = (values: number[]) => `[${values.join(", ")}]`;

/** Writes the binary banks to `output` and returns the TypeScript asset module. */
export function bakeAssets(manifest: Manifest, gameDirectory: string, output: string): string {
  mkdirSync(output, { recursive: true });
  const resource = loadGameResource(manifest, gameDirectory);
  const images = resource.images.slice(0, lastUsed(resource.images));
  const tilemaps = resource.tilemaps.slice(0, lastUsed(resource.tilemaps));
  const imagesFile = resolve(output, "images.bin");
  const tilemapsFile = resolve(output, "tilemaps.bin");
  writeFileSync(imagesFile, Buffer.concat(images));
  writeFileSync(tilemapsFile, Buffer.concat(tilemaps));

  const sounds: number[] = [],
    soundStarts: number[] = [];
  resource.sounds.forEach((sound) => {
    if (!sound) return void soundStarts.push(-1);
    soundStarts.push(sounds.length);
    sounds.push(sound.speed, sound.notes.length, sound.tones.length, sound.volumes.length, sound.effects.length);
    sounds.push(...sound.notes, ...sound.tones, ...sound.volumes, ...sound.effects);
  });
  const musics: number[] = [],
    musicStarts: number[] = [];
  resource.musics.forEach((music) => {
    if (!music) return void musicStarts.push(-1);
    musicStarts.push(musics.length);
    musics.push(...music.map((seq) => seq.length), ...music.flat());
  });

  const embed = (file: string, used: number) => (used ? `embedBytes(${JSON.stringify(file)})` : "[]");
  return `// Generated by tools/lib/assets.ts${manifest.resources ? ` from ${manifest.resources}` : ""}. Do not edit.
import { embedBytes, type i32, type u8 } from "@pocketjs/framework/solid/std";
export const IMAGES: u8[] = ${embed(imagesFile, images.length)};
export const TILEMAPS: u8[] = ${embed(tilemapsFile, tilemaps.length)};
export const TILEMAP_IMAGES: i32[] = ${list(resource.tilemapImages)};
export const COLORS: i32[] = ${list(resource.colors ?? [])};
export const SOUNDS: i32[] = ${list(sounds)};
export const SOUND_STARTS: i32[] = ${list(soundStarts)};
export const MUSICS: i32[] = ${list(musics)};
export const MUSIC_STARTS: i32[] = ${list(musicStarts)};
`;
}
