#!/usr/bin/env bun
/**
 * Builds a game directory into a GBA ROM:
 *
 * 1. bake the manifest's resources into the SDK's generated asset module;
 * 2. compile the game, the SDK and a generated root module with MicroTS;
 * 3. build the Rust model with the GBA runtime for thumbv4t-none-eabi;
 * 4. pack the ELF into a cartridge image under dist/.
 *
 *   bun tools/build.ts games/hello [--out dist] [--debug]
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { basename, relative, resolve } from "node:path";
import { elfToRom } from "./lib/rom.ts";
import { pocketjsRoot, microts } from "./lib/pocketjs.ts";
import { readManifest, type Manifest } from "./lib/manifest.ts";
import { bakeAssets } from "./lib/assets.ts";
import { flattenFunctions, iwramFunctions, placeInIwram } from "./lib/iwram.ts";

export const ROOT = resolve(import.meta.dir, "..");
export const GBA_TOOLCHAIN = "nightly-2026-07-01";
const SDK = resolve(ROOT, "sdk");

export interface BuildResult {
  rom: string;
  elf: string;
  manifest: Manifest;
}

async function run(command: string[], env: Record<string, string> = {}) {
  const child = Bun.spawn(command, { stdout: "inherit", stderr: "inherit", env: { ...process.env, ...env } });
  if ((await child.exited) !== 0) throw new Error(`command failed: ${command.join(" ")}`);
}

/** The root model: host entry points around the game's setup, update and draw. */
function rootModule(gameDirectory: string, manifest: Manifest): string {
  const entry = "./" + manifest.entry.replace(/\.ts$/, "");
  const host = relative(gameDirectory, resolve(SDK, "host")).replaceAll("\\", "/");
  return `// Generated by tools/build.ts.
import { setup, update, draw } from ${JSON.stringify(entry)};
import { boot as sdkBoot, beginFrame, endFrame } from ${JSON.stringify(host.startsWith(".") ? host : "./" + host)};
import type { i32 } from "@pocketjs/framework/solid/std";
export function boot(): void { sdkBoot(); setup(); }
export function frame(keys: i32, ticks: i32): void { beginFrame(keys, ticks); update(); draw(); endFrame(); }
`;
}

function gameCrate(model: string): { cargo: string; main: string } {
  const cargo = `[package]
name = "retro-game"
version = "0.1.0"
edition = "2021"
publish = false

[workspace]

[dependencies]
pocket-retro-gba = { path = ${JSON.stringify(resolve(ROOT, "runtime/gba"))} }
microts = { path = ${JSON.stringify(resolve(pocketjsRoot(), "engine/crates/microts"))}, features = ["critical-section"] }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
overflow-checks = false
debug = 1

[[bin]]
name = "game"
path = "src/main.rs"
test = false
bench = false
`;
  const main = `// Generated by tools/build.ts.
#![no_std]
#![no_main]

extern crate alloc;

#[path = ${JSON.stringify(model)}]
mod model;

use model::{AppModel, AppViewModel};
use pocket_retro_gba::{Game, Screen};

struct Model(alloc::boxed::Box<AppModel>);

impl Game for Model {
    fn boot(&mut self) {
        self.0.boot();
    }
    fn frame(&mut self, keys: u32, ticks: u32) {
        self.0.frame(keys as i32, ticks as i32);
    }
    fn screen(&self) -> Screen<'_> {
        Screen { pixels: self.0.hw_screen(), width: *self.0.hw_width() as usize, height: *self.0.hw_height() as usize }
    }
    fn screen_buffer(&mut self) -> &mut alloc::vec::Vec<u8> {
        self.0.hw_screen_mut()
    }
    fn colors(&self) -> &[i32] {
        self.0.hw_colors()
    }
    fn fps(&self) -> u32 {
        *self.0.hw_fps() as u32
    }
    fn voices(&mut self) -> &mut alloc::vec::Vec<i32> {
        self.0.hw_voices_mut()
    }
}

#[no_mangle]
extern "C" fn retro_game_main() -> ! {
    // The model and its first small arrays go to IWRAM, within 1.5 KiB, leaving
    // room for the screen, which the host moves there after boot. Where tagged
    // code leaves less, the arrays give way to a 160 x 120 screen if it fits.
    let (_, size) = pocket_retro_gba::memory::iwram_heap();
    let screen = 160 * 120 + 64 + core::mem::size_of::<AppModel>();
    let budget = if size >= screen { (size - screen).min(1536) } else { 1536 };
    let model = pocket_retro_gba::memory::in_iwram_up_to(512, budget, AppModel::default);
    let mut game = Model(pocket_retro_gba::memory::in_iwram(|| alloc::boxed::Box::new(model)));
    pocket_retro_gba::log!("model {} bytes", core::mem::size_of::<AppModel>());
    pocket_retro_gba::run(&mut game)
}
`;
  return { cargo, main };
}

export interface BuildOptions {
  out?: string;
  /** Keeps every generated model function out of line, so profiles attribute time to it. */
  noInline?: boolean;
}

export async function buildGame(gameDirectory: string, options: BuildOptions = {}): Promise<BuildResult> {
  gameDirectory = resolve(gameDirectory);
  const manifest = readManifest(gameDirectory);
  const name = basename(gameDirectory);
  const build = resolve(ROOT, "build", name);
  const out = resolve(options.out ?? resolve(ROOT, "dist"));
  mkdirSync(resolve(build, "gen"), { recursive: true });
  mkdirSync(resolve(build, "crate/src"), { recursive: true });
  mkdirSync(out, { recursive: true });

  // Generated modules replace the SDK's asset stub and supply the root model.
  const sources = new Map<string, string>();
  sources.set(resolve(SDK, "assets.ts"), bakeAssets(manifest, gameDirectory, resolve(build, "assets")));
  const entry = resolve(gameDirectory, "__main__.ts");
  sources.set(entry, rootModule(gameDirectory, manifest));

  const { analyzeModel, generateModelRust } = await microts();
  const program = analyzeModel(entry, { strict: true, name: "App", sources });
  for (const diagnostic of program.diagnostics)
    console.warn(
      `${diagnostic.file}:${diagnostic.line}:${diagnostic.column}: ${diagnostic.severity}: ${diagnostic.message}`,
    );
  const model = resolve(build, "gen/app_model.rs");
  const hot = placeInIwram(generateModelRust(program), iwramFunctions(SDK));
  const rust = options.noInline
    ? hot.rust.replace(/^(\s*)fn ((?:render_)?fn_\d+|pure_\d+)\(/gm, "$1#[inline(never)]\n$1fn $2(")
    : hot.rust;
  const names = new Map(
    [...rust.matchAll(/fn ((?:render_)?fn_\d+|pure_\d+)\([^\n]*\n\s*(?:self\.depth|depth)\.enter\("(\w+)"\);/g)].map(
      (m) => [m[1]!, m[2]!],
    ),
  );
  const flat = flattenFunctions(rust.replace(/#\[inline\(never\)\]\n(\s*)#\[inline\(never\)\]/g, "#[inline(never)]"));
  // Keep a name table for tools/profile.ts, since flattening drops the depth markers.
  writeFileSync(model, flat);
  writeFileSync(resolve(build, "gen/functions.json"), JSON.stringify(Object.fromEntries(names), null, 1));

  const crate = gameCrate(model);
  const manifestPath = resolve(build, "crate/Cargo.toml");
  if (!existsSync(manifestPath) || readFileSync(manifestPath, "utf8") !== crate.cargo)
    writeFileSync(manifestPath, crate.cargo);
  writeFileSync(resolve(build, "crate/src/main.rs"), crate.main);
  // Every game crate resolves the same dependencies; the checked-in lock pins them.
  const lock = resolve(ROOT, "runtime/gba/Cargo.lock");
  if (existsSync(lock)) writeFileSync(resolve(build, "crate/Cargo.lock"), readFileSync(lock));

  const target = resolve(ROOT, ".cache/gba-target");
  const rustflags = ["-C", `link-arg=-T${resolve(ROOT, "runtime/gba/gba.ld")}`, "-C", "link-arg=--gc-sections"];
  await run(
    [
      "cargo",
      `+${GBA_TOOLCHAIN}`,
      "build",
      "--locked",
      "--release",
      "--target",
      "thumbv4t-none-eabi",
      "-Z",
      "build-std=core,alloc",
      "--manifest-path",
      manifestPath,
      "--target-dir",
      target,
    ],
    { CARGO_ENCODED_RUSTFLAGS: rustflags.join("\x1f") },
  );
  const elf = resolve(out, `${name}.elf`);
  const rom = resolve(out, `${name}.gba`);
  const bytes = readFileSync(resolve(target, "thumbv4t-none-eabi/release/game"));
  writeFileSync(elf, bytes);
  writeFileSync(rom, elfToRom(bytes, { title: manifest.title, code: manifest.code }));
  return { rom, elf, manifest };
}

if (import.meta.main) {
  const args = process.argv.slice(2);
  const directory = args.find((arg) => !arg.startsWith("--"));
  if (!directory || args.includes("--help")) {
    console.log("bun tools/build.ts <game directory> [--out=<directory>] [--no-inline]");
    process.exit(directory ? 0 : 1);
  }
  const out = args.find((arg) => arg.startsWith("--out="))?.slice(6);
  const result = await buildGame(directory, { out, noInline: args.includes("--no-inline") });
  console.log(
    `${result.manifest.title}: ${relative(process.cwd(), result.rom)} (${readFileSync(result.rom).length} bytes)`,
  );
}
